import { IPatchNotes } from '.';

export const notes: IPatchNotes = {
  version: '1.1.20260311-1',
  title: '1.1.20260311-1',
  notes: [
    "追加: コメントの読み上げ停止機能 (#1165)",
    "追加: スポイト式カラーピッカーを追加 (#1138)",
    "追加: 設定ダイアログに目次(TOC)機能を実装 (#1102)",
    "変更: キャッシュ削除時にシーンコレクションを保持するよう変更 (#1173)",
    "修正: コメントサーバー再接続後にコメントが受信できない問題を修正 (#1167)",
    "",
    "Merge Commits:",
    "  - 追加: 設定ダイアログに目次(TOC)機能を実装 (30e877dfe)",
    "  - 修正: タブ再選択時にTOCセクションが重複する問題を修正 (4d64f3a85)",
    "  - 修正: TOCの長いラベルに省略記号を表示し、LanguageSettingsをTOCに追加 (f1fae707b)",
    "  - obs-studio-nodeの応答でAdvanced(詳細設定)のAudio(音声)が二つあるので統合 (22d70016f)",
    "  - Revert \"obs-studio-nodeの応答でAdvanced(詳細設定)のAudio(音声)が二つあるので統合\" (25ef5d4f9)",
    "  - 修正: TOCで連続する同名・同レベルのセクションを除外 (3772fa5c2)",
    "  - 修正: showSettings()経由での初期表示時にNavItemの行間が狭くなる問題を修正 (37a790442)",
    "  - 変更: TOC項目の行間を縮小してより多くの項目を表示 (764eaad54)",
    "  - 修正: showSettings()経由で開いた時に他カテゴリのTOCが混入する問題を修正 (c52607aef)",
    "  - 修正: TocSectionのテストをunregisterTocSectionの新シグネチャに対応 (75ba4b600)",
    "  - 追加: UntitledサブカテゴリのTOC表示対応 (b60cd73d3)",
    "  - 追加: ショートカットキータブのTOC表示対応 (6dc20fbfd)",
    "  - 修正: HotkeysタブのTOCでシーンとソースを親グループ配下に配置 (2b172c9ad)",
    "  - 修正: 設定項目が少ないタブからTOCを削除 (b76dc267f)",
    "  - リファクタ: TocManager.register()のposition判定処理を関数化 (5e197137a)",
    "  - 修正: GenericFormGroupsでUntitledセクションの順序を保持 (201193dea)",
    "  - Merge branch 'n-air_development' into feature/settings-toc (1f095a9b2)",
    "  - Merge branch 'n-air_development' into feature/settings-toc (59881270c)",
    "  - Merge branch 'n-air_development' into feature/settings-toc (0a3755ea8)",
    "  - 設定ダイアログの目次にスタイルを当てた (33af1cde8)",
    "  - コメント削除 (a036338d9)",
    "  - 追加: コメント読み上げ停止機能 (97a0b78eb)",
    "  - DEBUG: debug log (432d1b955)",
    "  - 修正: PRレビューコメント対応 (5f79f0081)",
    "  - 修正: スライダー入力欄のdisabled対応と文言修正 (7e8dfe3b0)",
    "  - 修正: 機能OFFで一時停止が即座に解除されない問題を修正 (486aaf7bf)",
    "  - 修正: 設定画面の開閉で「信号なし」が表示される問題を修正 (a105deabd)",
    "  - 修正: TestPlayback中に設定をOFFにしたときに即座にテストを終了する (9b6de5f91)",
    "  - 修正: 設定画面タブ切替時に「信号なし」が表示される問題を修正 (c375ce593)",
    "  - 修正: 未キャリブレート時の「最低音量を設定してください」表示を設定画面から削除 (d031e710e)",
    "  - 開発: json-cycleをsafeStringifyヘルパーに置き換えてデバッグログの循環参照を解決 (8cb56d881)",
    "  - Revert \"DEBUG: debug log\" (2b0ee443d)",
    "  - Merge branch 'n-air_development' into feature/unobtrusive-speech (67c864584)",
    "  - 追加: SoundDetector の Action Log を usage-statistics に追加 (dccaf04e7)",
    "  - 開発: ESLintエラーを修正 (535ec5efe)",
    "  - 修正: 放送者声検知による一時停止/再開時のコメント読み上げアイコン・ツールチップ表示を修正 (058ce538a)",
    "  - Merge branch 'n-air_development' into feature/unobtrusive-speech (ef099c6c5)",
    "  - Merge branch 'n-air_development' into feature/settings-toc (2acb0d4de)",
    "  - 修正: SoundDetectorService の設定値不正によるsilence/loud高速振動を修正 (a39d9abfb)",
    "  - 修正: resumeSilenceMs 変更時に loud 状態でコメント読み上げが誤って再開する問題を修正 (65a504f0d)",
    "  - 修正: シーン切り替え時に入力音声ソースのプルダウンが更新されない問題を修正 (4193e20cb)",
    "  - 修正: テスト連続再生中に実コメント読み上げが挟まるとテスト再生が停止する問題を修正 (3819d1000)",
    "  - Merge pull request #1165 from koizuka/feature/unobtrusive-speech (dee2e4df8)",
    "  - Merge branch 'n-air_development' into feature/settings-toc (28bbc0479)",
    "  - 開発: SoundDetectorSettings を TocSection に対応させる (9d187e2d1)",
    "  - Merge pull request #1102 from koizuka/feature/settings-toc (f2fd8484a)",
  ],
};
